const {
  withAndroidManifest,
  withMainApplication,
  withDangerousMod,
  AndroidConfig,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// One-way recovery for the withdrawn M15 themed-launcher-icon feature
// (expo-dynamic-app-icon + a `MainActivitylight` activity-alias).
//
// That feature enabled a second `MAIN`/`LAUNCHER` component and relied on a
// deferred, never-firing lifecycle hook to disable the first — leaving some
// installs with two launcher icons, and (when the disable *did* land) with
// `.MainActivity` stuck at COMPONENT_ENABLED_STATE_DISABLED. A disabled
// `.MainActivity` has no launcher entry and, worse, silently drops every
// deep link declared on it — including `zerodot-android://oauth/callback`,
// which is why sign-in "did nothing". `setComponentEnabledSetting` state
// survives an app update, and builds ship as a bare APK (no Play Store), so
// a normal reinstall-over-the-top would not clear it on its own.
//
// This plugin force-restores the canonical component state:
//   * on every process start (injected into MainApplication.onCreate), and
//   * the instant the APK is replaced (a MY_PACKAGE_REPLACED receiver) —
//     which reaches a device whose launcher icon is already gone and so
//     can't start the app the normal way.
//
// It is a no-op once the state is healthy and is safe to keep permanently.

const RECOVERY_CALL = "LauncherRecovery.restore(this)";

// Kotlin hard keywords that can appear as a package segment (0dot's package
// is `in.zerodot.android` — `in` needs backticking, exactly as the
// generated MainApplication.kt already does).
const KOTLIN_KEYWORDS = new Set([
  "in", "is", "as", "fun", "val", "var", "object", "class", "interface",
  "package", "typeof", "when", "if", "else", "for", "while", "do", "try",
  "this", "super", "null", "true", "false", "return", "throw",
]);

function kotlinPackage(pkg) {
  return pkg
    .split(".")
    .map((seg) => (KOTLIN_KEYWORDS.has(seg) ? `\`${seg}\`` : seg))
    .join(".");
}

function kotlinFile(pkg) {
  return `package ${kotlinPackage(pkg)}

import android.content.BroadcastReceiver
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager

// Generated by ./plugins/withAndroidLauncherRecovery.js — do not edit.
object LauncherRecovery {
  @JvmStatic
  fun restore(context: Context) {
    try {
      val pm = context.packageManager
      val pkg = context.packageName
      val main = ComponentName(pkg, "\$pkg.MainActivity")
      if (pm.getComponentEnabledSetting(main) != PackageManager.COMPONENT_ENABLED_STATE_ENABLED) {
        pm.setComponentEnabledSetting(
          main,
          PackageManager.COMPONENT_ENABLED_STATE_ENABLED,
          PackageManager.DONT_KILL_APP,
        )
      }
      // Best-effort: neutralise the legacy themed-icon alias if the package
      // manager still tracks an enabled state for it. Throws when the
      // component is unknown (the alias is gone from this manifest) — ignored.
      try {
        pm.setComponentEnabledSetting(
          ComponentName(pkg, "\$pkg.MainActivitylight"),
          PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
          PackageManager.DONT_KILL_APP,
        )
      } catch (ignored: Exception) {
      }
    } catch (ignored: Exception) {
    }
  }
}

class LauncherRecoveryReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    LauncherRecovery.restore(context)
  }
}
`;
}

module.exports = function withAndroidLauncherRecovery(config) {
  // 1. Emit the Kotlin source next to MainApplication.kt.
  config = withDangerousMod(config, [
    "android",
    (cfg) => {
      const pkg = cfg.android?.package;
      if (!pkg) throw new Error("withAndroidLauncherRecovery: android.package is not set");
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "java",
        ...pkg.split(".")
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "LauncherRecovery.kt"), kotlinFile(pkg));
      return cfg;
    },
  ]);

  // 2. Call it from MainApplication.onCreate (same package — no import
  //    needed). The MY_PACKAGE_REPLACED receiver below is the guaranteed
  //    recovery path; this just makes it also self-heal on every start. If
  //    the anchor ever stops matching after an Expo upgrade the injection
  //    silently no-ops (LauncherRecovery.kt still compiles unused) rather
  //    than breaking prebuild.
  config = withMainApplication(config, (cfg) => {
    const isKotlin = cfg.modResults.language === "kt";
    const call = isKotlin ? RECOVERY_CALL : "LauncherRecovery.restore(this);";
    let src = cfg.modResults.contents;
    if (!src.includes(call)) {
      const anchor = isKotlin ? "super.onCreate()\n" : "super.onCreate();\n";
      const at = src.indexOf(anchor);
      if (at !== -1) {
        const cut = at + anchor.length;
        src = `${src.slice(0, cut)}    ${call}\n${src.slice(cut)}`;
        cfg.modResults.contents = src;
      }
    }
    return cfg;
  });

  // 3. Register the MY_PACKAGE_REPLACED receiver.
  config = withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.receiver = (app.receiver || []).filter(
      (r) => r.$?.["android:name"] !== ".LauncherRecoveryReceiver"
    );
    app.receiver.push({
      $: {
        "android:name": ".LauncherRecoveryReceiver",
        "android:exported": "false",
        "android:enabled": "true",
      },
      "intent-filter": [
        {
          action: [{ $: { "android:name": "android.intent.action.MY_PACKAGE_REPLACED" } }],
        },
      ],
    });
    return cfg;
  });

  return config;
};
